// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AirBaseAirAttack = { stage_flag: Array<bigint>, squadron_plane: Array<bigint | null> | null, base_id: bigint, f_damage: AirDamage, e_damage: AirDamage, };

export type AirBaseAirAttacks = { attacks: Array<AirBaseAirAttack>, };

export type AirBaseAssult = { squadron_plane: Array<bigint>, f_damage: AirDamage, e_damage: AirDamage, };

export type AirDamage = { plane_from: Array<bigint> | null, touch_plane: bigint | null, loss_plane1: bigint, loss_plane2: bigint, damages: Array<number> | null, cl: Array<bigint> | null, sp: Array<Array<bigint> | null> | null, rai_flag: Array<bigint | null> | null, bak_flag: Array<bigint | null> | null, protect_flag: Array<boolean> | null, now_hps: Array<bigint>, };

export type AirFire = { use_item: Array<bigint>, idx: bigint, };

export type Battle = { battle_order: Array<BattleType> | null, timestamp: bigint | null, midnight_timestamp: bigint | null, cell_id: bigint, deck_id: bigint | null, formation: Array<bigint> | null, enemy_ship_id: Array<bigint> | null, e_params: Array<Array<bigint>> | null, e_slot: Array<Array<bigint>> | null, e_hp_max: Array<bigint> | null, f_total_damages: Array<bigint> | null, e_total_damages: Array<bigint> | null, friend_total_damages: Array<bigint> | null, midnight_f_total_damages: Array<bigint> | null, midnight_e_total_damages: Array<bigint> | null, reconnaissance: Array<bigint> | null, escape_idx: Array<bigint> | null, smoke_type: bigint | null, combat_ration: Array<bigint> | null, balloon_flag: bigint | null, air_base_assault: AirBaseAssult | null, carrier_base_assault: CarrierBaseAssault | null, air_base_air_attacks: AirBaseAirAttacks | null, opening_air_attack: OpeningAirAttack | null, support_attack: SupportAttack | null, opening_taisen: OpeningTaisen | null, opening_raigeki: OpeningRaigeki | null, hougeki: Array<Hougeki | null> | null, closing_raigeki: ClosingRaigeki | null, friendly_force_attack: FriendlyForceAttack | null, midnight_flare_pos: Array<bigint> | null, midngiht_touchplane: Array<bigint> | null, midnight_hougeki: MidnightHougeki | null, f_nowhps: Array<bigint> | null, e_nowhps: Array<bigint> | null, midngiht_f_nowhps: Array<bigint> | null, midngiht_e_nowhps: Array<bigint> | null, };

export type BattleType = { "AirBaseAssult": null } | { "CarrierBaseAssault": null } | { "AirBaseAirAttack": null } | { "OpeningAirAttack": null } | { "SupportAttack": null } | { "OpeningTaisen": null } | { "OpeningRaigeki": null } | { "Hougeki": bigint } | { "ClosingRaigeki": null } | { "FriendlyForceAttack": null } | { "MidnightHougeki": null };

export type Battles = { cells: Array<bigint>, battles: { [key in bigint]?: Battle }, };

export type CarrierBaseAssault = { f_damage: AirDamage, e_damage: AirDamage, };

export type ClosingRaigeki = { fdam: Array<number>, edam: Array<number>, frai: Array<bigint>, erai: Array<bigint>, fcl: Array<bigint>, ecl: Array<bigint>, f_protect_flag: Array<boolean>, e_protect_flag: Array<boolean>, f_now_hps: Array<bigint>, e_now_hps: Array<bigint>, };

export type FriendlyForceAttack = { fleet_info: FriendlyForceInfo, support_hourai: FriendlySupportHourai | null, };

export type FriendlyForceInfo = { slot_ex: Array<bigint>, max_hps: Array<bigint>, ship_id: Array<bigint>, params: Array<Array<bigint>>, ship_lv: Array<bigint>, now_hps: Array<bigint>, slot: Array<Array<bigint>>, };

export type FriendlySupportHourai = { flare_pos: Array<bigint>, hougeki: MidnightHougeki, };

export type Hougeki = { at_list: Array<bigint>, at_type: Array<bigint>, df_list: Array<Array<bigint>>, cl_list: Array<Array<bigint>>, damage: Array<Array<number>>, at_eflag: Array<bigint>, si_list: Array<Array<bigint | null>>, protect_flag: Array<Array<boolean>>, f_now_hps: Array<Array<bigint>>, e_now_hps: Array<Array<bigint>>, };

export type MidnightHougeki = { at_list: Array<bigint> | null, df_list: Array<Array<bigint>> | null, cl_list: Array<Array<bigint>> | null, damage: Array<Array<number>> | null, at_eflag: Array<bigint> | null, si_list: Array<Array<bigint | null>> | null, sp_list: Array<bigint> | null, protect_flag: Array<Array<boolean>> | null, f_now_hps: Array<Array<bigint>>, e_now_hps: Array<Array<bigint>>, };

export type OpeningAirAttack = { air_superiority: bigint | null, air_fire: AirFire | null, f_damage: AirDamage, e_damage: AirDamage, };

export type OpeningRaigeki = { fdam: Array<number>, edam: Array<number>, frai_list_items: Array<Array<bigint> | null>, erai_list_items: Array<Array<bigint> | null>, fcl_list: Array<bigint>, ecl_list: Array<bigint>, f_protect_flag: Array<boolean>, e_protect_flag: Array<boolean>, f_now_hps: Array<bigint>, e_now_hps: Array<bigint>, };

export type OpeningTaisen = { at_list: Array<bigint>, at_type: Array<bigint>, df_list: Array<Array<bigint>>, cl_list: Array<Array<bigint>>, damage: Array<Array<number>>, at_eflag: Array<bigint>, si_list: Array<Array<bigint | null>>, protect_flag: Array<Array<boolean>>, f_now_hps: Array<Array<bigint>>, e_now_hps: Array<Array<bigint>>, };

export type SupportAiratack = { deck_id: bigint, ship_id: Array<bigint>, f_damage: AirDamage, e_damage: AirDamage, };

export type SupportAttack = { support_hourai: SupportHourai | null, support_airatack: SupportAiratack | null, };

export type SupportHourai = { cl_list: Array<bigint>, damage: Array<number>, deck_id: bigint, ship_id: Array<bigint>, protect_flag: Array<boolean>, now_hps: Array<bigint>, };
