// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AirBaseAirAttack = { stage_flag: Array<number>, squadron_plane: Array<number | null> | null, base_id: number, f_damage: AirDamage, e_damage: AirDamage, };

export type AirBaseAirAttacks = { attacks: Array<AirBaseAirAttack>, };

export type AirBaseAssult = { squadron_plane: Array<number>, f_damage: AirDamage, e_damage: AirDamage, };

export type AirDamage = { plane_from: Array<number> | null, touch_plane: number | null, loss_plane1: number, loss_plane2: number, damages: Array<number> | null, cl: Array<number> | null, sp: Array<Array<number> | null> | null, rai_flag: Array<number | null> | null, bak_flag: Array<number | null> | null, protect_flag: Array<boolean> | null, now_hps: Array<number>, };

export type AirFire = { use_item: Array<number>, idx: number, };

export type Battle = { battle_order: Array<BattleType> | null, timestamp: number | null, midnight_timestamp: number | null, cell_id: number, deck_id: number | null, formation: Array<number> | null, enemy_ship_id: Array<number> | null, e_params: Array<Array<number>> | null, e_slot: Array<Array<number>> | null, e_hp_max: Array<number> | null, f_total_damages: Array<number> | null, e_total_damages: Array<number> | null, friend_total_damages: Array<number> | null, midnight_f_total_damages: Array<number> | null, midnight_e_total_damages: Array<number> | null, reconnaissance: Array<number> | null, escape_idx: Array<number> | null, smoke_type: number | null, combat_ration: Array<number> | null, balloon_flag: number | null, air_base_assault: AirBaseAssult | null, carrier_base_assault: CarrierBaseAssault | null, air_base_air_attacks: AirBaseAirAttacks | null, opening_air_attack: OpeningAirAttack | null, support_attack: SupportAttack | null, opening_taisen: OpeningTaisen | null, opening_raigeki: OpeningRaigeki | null, hougeki: Array<Hougeki | null> | null, closing_raigeki: ClosingRaigeki | null, friendly_force_attack: FriendlyForceAttack | null, midnight_flare_pos: Array<number> | null, midngiht_touchplane: Array<number> | null, midnight_hougeki: MidnightHougeki | null, f_nowhps: Array<number> | null, e_nowhps: Array<number> | null, midngiht_f_nowhps: Array<number> | null, midngiht_e_nowhps: Array<number> | null, };

export type BattleType = { "AirBaseAssult": null } | { "CarrierBaseAssault": null } | { "AirBaseAirAttack": null } | { "OpeningAirAttack": null } | { "SupportAttack": null } | { "OpeningTaisen": null } | { "OpeningRaigeki": null } | { "Hougeki": number } | { "ClosingRaigeki": null } | { "FriendlyForceAttack": null } | { "MidnightHougeki": null };

export type Battles = { cells: Array<number>, battles: { [key in number]?: Battle }, };

export type CarrierBaseAssault = { f_damage: AirDamage, e_damage: AirDamage, };

export type ClosingRaigeki = { fdam: Array<number>, edam: Array<number>, frai: Array<number>, erai: Array<number>, fcl: Array<number>, ecl: Array<number>, f_protect_flag: Array<boolean>, e_protect_flag: Array<boolean>, f_now_hps: Array<number>, e_now_hps: Array<number>, };

export type FriendlyForceAttack = { fleet_info: FriendlyForceInfo, support_hourai: FriendlySupportHourai | null, };

export type FriendlyForceInfo = { slot_ex: Array<number>, max_hps: Array<number>, ship_id: Array<number>, params: Array<Array<number>>, ship_lv: Array<number>, now_hps: Array<number>, slot: Array<Array<number>>, };

export type FriendlySupportHourai = { flare_pos: Array<number>, hougeki: MidnightHougeki, };

export type Hougeki = { at_list: Array<number>, at_type: Array<number>, df_list: Array<Array<number>>, cl_list: Array<Array<number>>, damage: Array<Array<number>>, at_eflag: Array<number>, si_list: Array<Array<number | null>>, protect_flag: Array<Array<boolean>>, f_now_hps: Array<Array<number>>, e_now_hps: Array<Array<number>>, };

export type MidnightHougeki = { at_list: Array<number> | null, df_list: Array<Array<number>> | null, cl_list: Array<Array<number>> | null, damage: Array<Array<number>> | null, at_eflag: Array<number> | null, si_list: Array<Array<number | null>> | null, sp_list: Array<number> | null, protect_flag: Array<Array<boolean>> | null, f_now_hps: Array<Array<number>>, e_now_hps: Array<Array<number>>, };

export type OpeningAirAttack = { air_superiority: number | null, air_fire: AirFire | null, f_damage: AirDamage, e_damage: AirDamage, };

export type OpeningRaigeki = { fdam: Array<number>, edam: Array<number>, frai_list_items: Array<Array<number> | null>, erai_list_items: Array<Array<number> | null>, fcl_list: Array<number>, ecl_list: Array<number>, f_protect_flag: Array<boolean>, e_protect_flag: Array<boolean>, f_now_hps: Array<number>, e_now_hps: Array<number>, };

export type OpeningTaisen = { at_list: Array<number>, at_type: Array<number>, df_list: Array<Array<number>>, cl_list: Array<Array<number>>, damage: Array<Array<number>>, at_eflag: Array<number>, si_list: Array<Array<number | null>>, protect_flag: Array<Array<boolean>>, f_now_hps: Array<Array<number>>, e_now_hps: Array<Array<number>>, };

export type SupportAiratack = { deck_id: number, ship_id: Array<number>, f_damage: AirDamage, e_damage: AirDamage, };

export type SupportAttack = { support_hourai: SupportHourai | null, support_airatack: SupportAiratack | null, };

export type SupportHourai = { cl_list: Array<number>, damage: Array<number>, deck_id: number, ship_id: Array<number>, protect_flag: Array<boolean>, now_hps: Array<number>, };
