// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AirDamage, Battle } from "./battle";

export type AirBaseAttack = { air_superiority: bigint | null, plane_from: Array<Array<bigint> | null>, f_damage: AirDamage, e_damage: AirDamage, stage_flag: Array<bigint>, map_squadron_plane: { [key in string]?: Array<bigint> } | null, };

export type Cell = { timestamp: bigint | null, rashin_id: bigint, no: bigint, color_no: bigint, event_id: bigint, event_kind: bigint, next: bigint, e_deck_info: Array<EDeckInfo> | null, limit_state: bigint, m1: bigint | null, destruction_battle: DestructionBattle | null, happening: Happening | null, };

export type CellData = { id: bigint, no: bigint, color_no: bigint, passed: bigint, distance: bigint | null, };

export type Cells = { maparea_id: bigint, mapinfo_no: bigint, bosscell_no: bigint, bosscomp: bigint, cells: { [key in bigint]?: Cell }, cell_index: Array<bigint>, event_map: Eventmap | null, cell_data: Array<CellData>, battles: { [key in bigint]?: Battle }, };

export type DestructionBattle = { formation: Array<bigint>, ship_ke: Array<bigint>, ship_lv: Array<bigint>, e_nowhps: Array<bigint>, e_maxhps: Array<bigint>, e_slot: Array<Array<bigint>>, f_nowhps: Array<bigint>, f_maxhps: Array<bigint>, air_base_attack: AirBaseAttack, lost_kind: bigint, f_total_damages: Array<bigint> | null, e_total_damages: Array<bigint> | null, };

export type EDeckInfo = { kind: bigint, ship_ids: Array<bigint>, };

export type Eventmap = { max_maphp: bigint, now_maphp: bigint, dmg: bigint, };

export type Happening = { count: bigint, mst_id: bigint, dentan: bigint, };
