// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AirDamage, Battle } from "./battle";

export type AirBaseAttack = { air_superiority: number | null, plane_from: Array<Array<number> | null>, f_damage: AirDamage, e_damage: AirDamage, stage_flag: Array<number>, map_squadron_plane: { [key in string]?: Array<number> } | null, };

export type Cell = { timestamp: number | null, rashin_id: number, no: number, color_no: number, event_id: number, event_kind: number, next: number, e_deck_info: Array<EDeckInfo> | null, limit_state: number, m1: number | null, destruction_battle: DestructionBattle | null, happening: Happening | null, };

export type CellData = { id: number, no: number, color_no: number, passed: number, distance: number | null, };

export type Cells = { maparea_id: number, mapinfo_no: number, bosscell_no: number, bosscomp: number, cells: { [key in number]?: Cell }, cell_index: Array<number>, event_map: Eventmap | null, cell_data: Array<CellData>, battles: { [key in number]?: Battle }, };

export type DestructionBattle = { formation: Array<number>, ship_ke: Array<number>, ship_lv: Array<number>, e_nowhps: Array<number>, e_maxhps: Array<number>, e_slot: Array<Array<number>>, f_nowhps: Array<number>, f_maxhps: Array<number>, air_base_attack: AirBaseAttack, lost_kind: number, f_total_damages: Array<number> | null, e_total_damages: Array<number> | null, };

export type EDeckInfo = { kind: number, ship_ids: Array<number>, };

export type Eventmap = { max_maphp: number, now_maphp: number, dmg: number, };

export type Happening = { count: number, mst_id: number, dentan: number, };
