// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MstEquipExslot = { equip: bigint, };

export type MstEquipExslotShip = { ship_ids: { [key in string]?: bigint } | null, stypes: { [key in string]?: bigint } | null, ctypes: { [key in string]?: bigint } | null, req_level: bigint, };

export type MstEquipExslotShips = { mst_equip_ships: { [key in string]?: MstEquipExslotShip }, };

export type MstEquipExslots = { mst_equip_exslots: { [key in bigint]?: MstEquipExslot }, };

export type MstEquipLimitExslot = { equip: Array<bigint>, };

export type MstEquipLimitExslots = { mst_equip_limit_exslots: { [key in bigint]?: MstEquipLimitExslot }, };

export type MstEquipShip = { equip_type: { [key in string]?: Array<bigint> | null }, };

export type MstEquipShips = { mst_equip_ships: { [key in bigint]?: MstEquipShip }, };

export type MstMapArea = { api_id: bigint, api_name: string, api_type: bigint, };

export type MstMapAreas = { mst_map_areas: { [key in bigint]?: MstMapArea }, };

export type MstMapInfo = { id: bigint, maparea_id: bigint, no: bigint, name: string, level: bigint, opetext: string, infotext: string, item: Array<bigint>, max_maphp: bigint | null, required_defeat_count: bigint | null, sally_flag: Array<bigint>, };

export type MstMapInfos = { mst_map_infos: { [key in bigint]?: MstMapInfo }, };

export type MstShip = { id: bigint, sortno: bigint | null, sort_id: bigint, name: string, yomi: string, stype: bigint, ctype: bigint, afterlv: bigint | null, aftershipid: string | null, taik: Array<bigint> | null, souk: Array<bigint> | null, houg: Array<bigint> | null, raig: Array<bigint> | null, tyku: Array<bigint> | null, luck: Array<bigint> | null, soku: bigint, leng: bigint | null, slot_num: bigint, maxeq: Array<bigint> | null, buildtime: bigint | null, broken: Array<bigint> | null, powup: Array<bigint> | null, backs: bigint | null, getmes: string | null, afterfuel: bigint | null, afterbull: bigint | null, fuel_max: bigint | null, bull_max: bigint | null, voicef: bigint | null, tais: Array<bigint> | null, };

export type MstShipGraph = { api_id: bigint, api_filename: string, api_version: Array<string>, api_battle_n: Array<bigint> | null, api_battle_d: Array<bigint> | null, api_sortno: bigint | null, api_boko_n: Array<bigint> | null, api_boko_d: Array<bigint> | null, api_kaisyu_n: Array<bigint> | null, api_kaisyu_d: Array<bigint> | null, api_kaizo_n: Array<bigint> | null, api_kaizo_d: Array<bigint> | null, api_map_n: Array<bigint> | null, api_map_d: Array<bigint> | null, api_ensyuf_n: Array<bigint> | null, api_ensyuf_d: Array<bigint> | null, api_ensyue_n: Array<bigint> | null, api_weda: Array<bigint> | null, api_wedb: Array<bigint> | null, api_pa: Array<bigint> | null, api_pab: Array<bigint> | null, api_sp_flag: bigint | null, api_wedc: Array<bigint> | null, api_wedd: Array<bigint> | null, };

export type MstShipGraphs = { mst_ship_graphs: { [key in bigint]?: MstShipGraph }, };

export type MstShipUpgrade = { api_id: bigint, api_current_ship_id: bigint, api_original_ship_id: bigint, api_upgrade_type: bigint, api_upgrade_level: bigint, api_drawing_count: bigint, api_catapult_count: bigint, api_report_count: bigint, api_aviation_mat_count: bigint, api_arms_mat_count: bigint, api_tech_count: bigint, api_sortno: bigint, api_boiler_count: bigint | null, };

export type MstShipUpgrades = { mst_ship_upgrades: { [key in bigint]?: MstShipUpgrade }, };

export type MstShips = { mst_ships: { [key in bigint]?: MstShip }, };

export type MstSlotItem = { id: bigint, sortno: bigint, name: string, _type: Array<bigint>, taik: bigint, souk: bigint, houg: bigint, raig: bigint, soku: bigint, baku: bigint, tyku: bigint, tais: bigint, atap: bigint, houm: bigint, raim: bigint, houk: bigint, raik: bigint, bakk: bigint, saku: bigint, sakb: bigint, luck: bigint, leng: bigint, rare: bigint, taibaku: bigint, geigeki: bigint, broken: Array<bigint>, usebull: string, version: bigint | null, cost: bigint | null, distance: bigint | null, };

export type MstSlotItemEquipType = { id: bigint, name: string, };

export type MstSlotItemEquipTypes = { mst_slotitem_equip_types: { [key in bigint]?: MstSlotItemEquipType }, };

export type MstSlotItems = { mst_slot_items: { [key in bigint]?: MstSlotItem }, };

export type MstStype = { id: bigint, sortno: bigint, name: string, equip_type: { [key in string]?: bigint }, };

export type MstStypes = { mst_stypes: { [key in bigint]?: MstStype }, };

export type MstUseItem = { id: bigint, name: string, };

export type MstUseItems = { mst_use_items: { [key in bigint]?: MstUseItem }, };
