// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AirBase = { rid: number, action_kind: number, area_id: number, name: string, distance: number, plane_info: Array<PlaneInfo>, };

export type AirBases = { bases: { [key in string]?: AirBase }, };

export type PlaneInfo = { cond: number | null, state: number, max_count: number | null, count: number | null, slotid: number, squadron_id: number, };
