// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeckPort = { id: number, name: string, mission: Array<number>, ship: Array<number> | null, };

export type DeckPorts = { deck_ports: { [key in number]?: DeckPort }, combined_flag: number | null, };

export type Logs = { message: Array<string> | null, };

export type Materials = { materials: { [key in number]?: number }, };

export type Mission = { mission_id: number, complete_time: number, counter: number, };

export type NDock = { ship_id: number, complete_time: number, counter: number, item1: number, item2: number, item3: number, item4: number, };

export type NDocks = { n_docks: Array<NDock>, };

export type Ship = { id: number, ship_id: number | null, lv: number | null, exp: Array<number> | null, nowhp: number | null, maxhp: number | null, soku: number | null, leng: number | null, slot: Array<number> | null, onslot: Array<number> | null, slot_ex: number | null, fuel: number | null, bull: number | null, slotnum: number | null, cond: number | null, karyoku: Array<number> | null, raisou: Array<number> | null, taiku: Array<number> | null, soukou: Array<number> | null, kaihi: Array<number> | null, taisen: Array<number> | null, sakuteki: Array<number> | null, lucky: Array<number> | null, sally_area: number | null, sp_effect_items: SpEffectItems | null, };

export type Ships = { ships: { [key in number]?: Ship }, };

export type SpEffectItem = { kind: number, raig: number | null, souk: number | null, houg: number | null, kaih: number | null, };

export type SpEffectItems = { items: { [key in number]?: SpEffectItem }, };
