// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeckPort = { id: bigint, name: string, mission: Array<bigint>, ship: Array<bigint> | null, };

export type DeckPorts = { deck_ports: { [key in bigint]?: DeckPort }, combined_flag: bigint | null, };

export type Logs = { message: Array<string> | null, };

export type Materials = { materials: { [key in number]?: bigint }, };

export type Mission = { mission_id: bigint, complete_time: bigint, counter: bigint, };

export type NDock = { ship_id: bigint, complete_time: bigint, counter: bigint, item1: bigint, item2: bigint, item3: bigint, item4: bigint, };

export type NDocks = { n_docks: Array<NDock>, };

export type Ship = { id: bigint, ship_id: bigint | null, lv: bigint | null, exp: Array<bigint> | null, nowhp: bigint | null, maxhp: bigint | null, soku: bigint | null, leng: bigint | null, slot: Array<bigint> | null, onsolot: Array<bigint> | null, slot_ex: bigint | null, fuel: bigint | null, bull: bigint | null, slotnum: bigint | null, cond: bigint | null, karyoku: Array<bigint> | null, raisou: Array<bigint> | null, taiku: Array<bigint> | null, soukou: Array<bigint> | null, kaihi: Array<bigint> | null, taisen: Array<bigint> | null, sakuteki: Array<bigint> | null, lucky: Array<bigint> | null, sally_area: bigint | null, sp_effect_items: SpEffectItems | null, };

export type Ships = { ships: { [key in bigint]?: Ship }, };

export type SpEffectItem = { kind: bigint, raig: bigint | null, souk: bigint | null, houg: bigint | null, kaih: bigint | null, };

export type SpEffectItems = { items: { [key in bigint]?: SpEffectItem }, };
