// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Quest = { no: number, category: number, quest_type: number, label_type: number, state: number, title: string, detail: string, voice_id: number, get_material: Array<number>, bonus_flag: number, progress_flag: number, invalid_flag: number, lost_badges: number | null, };

export type QuestCompletion = { no: number, state: number, progress_flag: number, c_flag: number, };

export type Quests = { timestamp: number | null, page_no: number, count: number, completed_kind: number, exec_count: number, exec_type: number, quests: { [key in number]?: Quest }, completed: { [key in number]?: QuestCompletion }, };
