// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SlotItem = { id: bigint, slotitem_id: bigint, locked: bigint, level: bigint, alv: bigint | null, };

export type SlotItems = { slot_items: { [key in bigint]?: SlotItem }, };

export type UseItem = { id: bigint, count: bigint, };

export type UseItems = { use_items: { [key in bigint]?: UseItem }, };
