// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SlotItem = { id: number, slotitem_id: number, locked: number, level: number, alv: number | null, };

export type SlotItems = { slot_items: { [key in number]?: SlotItem }, };

export type UseItem = { id: number, count: number, };

export type UseItems = { use_items: { [key in number]?: UseItem }, };
