
import json
import os
from pathlib import Path

# Paths
ROOT_DIR = Path(__file__).resolve().parent.parent.parent.parent
SOURCE_JSON = ROOT_DIR / "packages/FUSOU-WORKFLOW/schemas/kc_api_v1.json"
TARGET_PY = ROOT_DIR / "packages/fusou-datasets/python/fusou_datasets/schema.py"

# Manual Master Data Definitions (since they aren't in kc_api_v1.json)
MASTER_TABLES = {
    "ship_type": ["id", "name", "sort_no", "mission_type"],
    "ship_master": ["id", "name", "yomi", "stype", "ctype", "max_hp", "karyoku", "raisou", "taiku", "soukou"],
    "slot_item_master": ["id", "name", "type", "soukou", "karyoku", "raisou", "baku", "taiku", "taisen", "sakuteki", "houm", "houk", "kouku", "distance", "cost"],
    "use_item_master": ["id", "name", "description"],
    "map_area_master": ["id", "name"],
    "map_info_master": ["id", "maparea_id", "no", "name", "level"],
    "mission_master": ["id", "maparea_id", "name", "details", "time", "difficulty", "use_fuel", "use_bull", "return_flag"],
}

def to_class_name(s):
    return "".join(word.capitalize() for word in s.split("_"))

def generate():
    print(f"Reading {SOURCE_JSON}...")
    with open(SOURCE_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)

    lines = [
        "# Auto-generated by scripts/gen_python_constants.py",
        "# Do not edit manually.",
        "",
        "class Column(str):",
        "    \"\"\"String subclass that carries table metadata.\"\"\"",
        "    def __new__(cls, value: str, table: str) -> \"Column\":",
        "        obj = str.__new__(cls, value)",
        "        obj.table = table",
        "        return obj",
        "",
        "class Tables:",
        "    \"\"\"",
        "    Type-safe table and column constants.",
        "    Usage:",
        "        from fusou_datasets import Tables",
        "        df = fusou_datasets.load(Tables.Battle.TABLE)",
        "        print(df[Tables.Battle.TIMESTAMP])",
        "    \"\"\"",
        "",
    ]

    # Process Ingest Data (Battle Logs)
    lines.append("    # --- Battle / Log Data ---")
    
    schemas = data.get("schemas", [])
    # Sort for stability
    schemas.sort(key=lambda x: x["table_name"])

    for item in schemas:
        table_name = item["table_name"]
        class_name = to_class_name(table_name)
        
        # Parse inner Avro schema string
        try:
            avro_schema = json.loads(item["schema"])
            fields = avro_schema.get("fields", [])
        except (json.JSONDecodeError, TypeError):
            print(f"Warning: Failed to parse schema for {table_name}")
            fields = []

        lines.append(f"    class {class_name}:")
        lines.append(f"        TABLE = \"{table_name}\"")
        for field in fields:
            f_name = field["name"]
            prop_name = f_name.upper()
            # Use Column class
            lines.append(f"        {prop_name} = Column(\"{f_name}\", \"{table_name}\")")
        lines.append("")

    # Process Master Data
    lines.append("    # --- Master Data (Manual) ---")
    for table_name, columns in sorted(MASTER_TABLES.items()):
        class_name = to_class_name(table_name)
        lines.append(f"    class {class_name}:")
        lines.append(f"        TABLE = \"{table_name}\"")
        for f_name in columns:
            prop_name = f_name.upper()
            lines.append(f"        {prop_name} = Column(\"{f_name}\", \"{table_name}\")")
        lines.append("")

    print(f"Writing to {TARGET_PY}...")
    with open(TARGET_PY, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("Done.")

if __name__ == "__main__":
    generate()
