import type { Battle, Battles } from "../battle";

export const default_battles: Battles = {
  cells: [],
  battles: {},
};

export const default_battle: Battle = {
  cell_id: 0,
  deck_id: 0,
  formation: [],
  enemy_ship_id: [],
  e_params: [],
  e_slot: [],
  e_hp_max: [],
  reconnaissance: [],
  escape_idx: [],
  smoke_type: null,
  air_base_air_attacks: {
    attacks: [],
  },
  opening_air_attack: {
    air_superiority: 0,
    air_fire: {
      use_item: [],
      idx: -1,
    },
    f_damage: {
      plane_from: [],
      touch_plane: 0,
      loss_plane1: 0,
      loss_plane2: 0,
      damages: [],
      cl: [],
      sp: [],
      rai_flag: [],
      bak_flag: [],
      protect_flag: [],
      now_hps: [],
    },
    e_damage: {
      plane_from: [],
      touch_plane: 0,
      loss_plane1: 0,
      loss_plane2: 0,
      damages: [],
      cl: [],
      sp: [],
      rai_flag: [],
      bak_flag: [],
      protect_flag: [],
      now_hps: [],
    },
  },
  support_attack: {
    support_hourai: {
      cl_list: [],
      damage: [],
      deck_id: 0,
      ship_id: [],
      protect_flag: [],
      now_hps: [],
    },
    support_airatack: {
      deck_id: 0,
      ship_id: [],
      f_damage: {
        plane_from: [],
        touch_plane: 0,
        loss_plane1: 0,
        loss_plane2: 0,
        damages: [],
        cl: [],
        sp: [],
        rai_flag: [],
        bak_flag: [],
        protect_flag: [],
        now_hps: [],
      },
      e_damage: {
        plane_from: [],
        touch_plane: 0,
        loss_plane1: 0,
        loss_plane2: 0,
        damages: [],
        cl: [],
        sp: [],
        rai_flag: [],
        bak_flag: [],
        protect_flag: [],
        now_hps: [],
      },
    },
  },
  opening_taisen: {
    at_list: [],
    at_type: [],
    df_list: [],
    cl_list: [],
    damage: [],
    at_eflag: [],
    si_list: [],
    protect_flag: [],
    f_now_hps: [],
    e_now_hps: [],
  },
  opening_raigeki: {
    fdam: [],
    edam: [],
    frai_list_items: [[]],
    erai_list_items: [[]],
    fcl_list: [],
    ecl_list: [],
    f_protect_flag: [],
    e_protect_flag: [],
    f_now_hps: [],
    e_now_hps: [],
  },
  hougeki: [],
  closing_raigeki: {
    fdam: [],
    edam: [],
    frai: [],
    erai: [],
    fcl: [],
    ecl: [],
    f_protect_flag: [],
    e_protect_flag: [],
    f_now_hps: [],
    e_now_hps: [],
  },
  midngiht_touchplane: [],
  midnight_flare_pos: [],
  midnight_hougeki: {
    at_list: [],
    df_list: [[]],
    cl_list: [[]],
    damage: [[]],
    at_eflag: [],
    si_list: [[]],
    sp_list: [],
    protect_flag: [[]],
    f_now_hps: [],
    e_now_hps: [],
  },
  air_base_assault: null,
  carrier_base_assault: null,
  friendly_force_attack: null,
  f_nowhps: null,
  e_nowhps: null,
  midngiht_f_nowhps: null,
  midngiht_e_nowhps: null,
  f_total_damages: null,
  e_total_damages: null,
  friend_total_damages: null,
  battle_order: null,
  midnight_f_total_damages: null,
  midnight_e_total_damages: null,
  combat_ration: null,
  balloon_flag: null,
  timestamp: null,
  midnight_timestamp: null,
};
