// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MstEquipExslot = { equip: number, };

export type MstEquipExslotShip = { ship_ids: { [key in string]?: number } | null, stypes: { [key in string]?: number } | null, ctypes: { [key in string]?: number } | null, req_level: number, };

export type MstEquipExslotShips = { mst_equip_ships: { [key in string]?: MstEquipExslotShip }, };

export type MstEquipExslots = { mst_equip_exslots: { [key in number]?: MstEquipExslot }, };

export type MstEquipLimitExslot = { equip: Array<number>, };

export type MstEquipLimitExslots = { mst_equip_limit_exslots: { [key in number]?: MstEquipLimitExslot }, };

export type MstEquipShip = { equip_type: { [key in string]?: Array<number> | null }, };

export type MstEquipShips = { mst_equip_ships: { [key in number]?: MstEquipShip }, };

export type MstMapArea = { api_id: number, api_name: string, api_type: number, };

export type MstMapAreas = { mst_map_areas: { [key in number]?: MstMapArea }, };

export type MstMapInfo = { id: number, maparea_id: number, no: number, name: string, level: number, opetext: string, infotext: string, item: Array<number>, max_maphp: number | null, required_defeat_count: number | null, sally_flag: Array<number>, };

export type MstMapInfos = { mst_map_infos: { [key in number]?: MstMapInfo }, };

export type MstShip = { id: number, sortno: number | null, sort_id: number, name: string, yomi: string, stype: number, ctype: number, afterlv: number | null, aftershipid: string | null, taik: Array<number> | null, souk: Array<number> | null, houg: Array<number> | null, raig: Array<number> | null, tyku: Array<number> | null, luck: Array<number> | null, soku: number, leng: number | null, slot_num: number, maxeq: Array<number> | null, buildtime: number | null, broken: Array<number> | null, powup: Array<number> | null, backs: number | null, getmes: string | null, afterfuel: number | null, afterbull: number | null, fuel_max: number | null, bull_max: number | null, voicef: number | null, tais: Array<number> | null, };

export type MstShipGraph = { api_id: number, api_filename: string, api_version: Array<string>, api_battle_n: Array<number> | null, api_battle_d: Array<number> | null, api_sortno: number | null, api_boko_n: Array<number> | null, api_boko_d: Array<number> | null, api_kaisyu_n: Array<number> | null, api_kaisyu_d: Array<number> | null, api_kaizo_n: Array<number> | null, api_kaizo_d: Array<number> | null, api_map_n: Array<number> | null, api_map_d: Array<number> | null, api_ensyuf_n: Array<number> | null, api_ensyuf_d: Array<number> | null, api_ensyue_n: Array<number> | null, api_weda: Array<number> | null, api_wedb: Array<number> | null, api_pa: Array<number> | null, api_pab: Array<number> | null, api_sp_flag: number | null, api_wedc: Array<number> | null, api_wedd: Array<number> | null, };

export type MstShipGraphs = { mst_ship_graphs: { [key in number]?: MstShipGraph }, };

export type MstShipUpgrade = { api_id: number, api_current_ship_id: number, api_original_ship_id: number, api_upgrade_type: number, api_upgrade_level: number, api_drawing_count: number, api_catapult_count: number, api_report_count: number, api_aviation_mat_count: number, api_arms_mat_count: number, api_tech_count: number, api_sortno: number, api_boiler_count: number | null, };

export type MstShipUpgrades = { mst_ship_upgrades: { [key in number]?: MstShipUpgrade }, };

export type MstShips = { mst_ships: { [key in number]?: MstShip }, };

export type MstSlotItem = { id: number, sortno: number, name: string, type: Array<number>, taik: number, souk: number, houg: number, raig: number, soku: number, baku: number, tyku: number, tais: number, atap: number, houm: number, raim: number, houk: number, raik: number, bakk: number, saku: number, sakb: number, luck: number, leng: number, rare: number, taibaku: number, geigeki: number, broken: Array<number>, usebull: string, version: number | null, cost: number | null, distance: number | null, };

export type MstSlotItemEquipType = { id: number, name: string, };

export type MstSlotItemEquipTypes = { mst_slotitem_equip_types: { [key in number]?: MstSlotItemEquipType }, };

export type MstSlotItems = { mst_slot_items: { [key in number]?: MstSlotItem }, };

export type MstStype = { id: number, sortno: number, name: string, equip_type: { [key in string]?: number }, };

export type MstStypes = { mst_stypes: { [key in number]?: MstStype }, };

export type MstUseItem = { id: number, name: string, };

export type MstUseItems = { mst_use_items: { [key in number]?: MstUseItem }, };
