// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AirBase = { rid: bigint, action_kind: bigint, area_id: bigint, name: string, distance: bigint, plane_info: Array<PlaneInfo>, };

export type AirBases = { bases: { [key in string]?: AirBase }, };

export type PlaneInfo = { cond: bigint | null, state: bigint, max_count: bigint | null, count: bigint | null, slotid: bigint, squadron_id: bigint, };
