// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Quest = { no: bigint, category: bigint, quest_type: bigint, label_type: bigint, state: bigint, title: string, detail: string, voice_id: bigint, get_material: Array<bigint>, bonus_flag: bigint, progress_flag: bigint, invalid_flag: bigint, lost_badges: bigint | null, };

export type QuestCompletion = { no: bigint, state: bigint, progress_flag: bigint, c_flag: bigint, };

export type Quests = { timestamp: bigint | null, page_no: bigint, count: bigint, completed_kind: bigint, exec_count: bigint, exec_type: bigint, quests: { [key in bigint]?: Quest }, completed: { [key in bigint]?: QuestCompletion }, };
