import { MASTER_DATA_TABLES, PUBLIC_RECORD_TABLES } from "../contracts";

const SCHEMA_NAMES: Readonly<Record<string, string>> = {
  airbase: "AirBase",
  airbase_airattack: "AirBaseAirAttack",
  airbase_airattack_list: "AirBaseAirAttackList",
  airbase_assult: "AirBaseAssult",
  battle: "Battle",
  battle_result: "BattleResult",
  carrierbase_assault: "CarrierBaseAssault",
  cells: "Cells",
  closing_raigeki: "ClosingRaigeki",
  destruction_battle: "DestructionBattle",
  enemy_deck: "EnemyDeck",
  enemy_ship: "EnemyShip",
  enemy_slotitem: "EnemySlotItem",
  env_info: "EnvInfo",
  friend_deck: "FriendDeck",
  friend_ship: "FriendShip",
  friend_slotitem: "FriendSlotItem",
  friendly_support_hourai: "FriendlySupportHourai",
  friendly_support_hourai_list: "FriendlySupportHouraiList",
  hougeki: "Hougeki",
  hougeki_list: "HougekiList",
  midnight_hougeki: "MidnightHougeki",
  midnight_hougeki_list: "MidnightHougekiList",
  mst_equip_exslot: "MstEquipExslot",
  mst_equip_exslot_ship: "MstEquipExslotShip",
  mst_equip_exslot_ships: "MstEquipExslotShip",
  mst_equip_limit_exslot: "MstEquipLimitExslot",
  mst_equip_ship: "MstEquipShip",
  mst_equip_ships: "MstEquipShip",
  mst_map_area: "MstMapArea",
  mst_map_areas: "MstMapArea",
  mst_map_info: "MstMapInfo",
  mst_map_infos: "MstMapInfo",
  mst_ship: "MstShip",
  mst_ship_graph: "MstShipGraph",
  mst_ship_graphs: "MstShipGraph",
  mst_ship_upgrade: "MstShipUpgrade",
  mst_ship_upgrades: "MstShipUpgrade",
  mst_ships: "MstShip",
  mst_slot_item: "MstSlotItem",
  mst_slot_item_equip_type: "MstSlotItemEquipType",
  mst_slot_items: "MstSlotItem",
  mst_slotitem_equip_types: "MstSlotItemEquipType",
  mst_stype: "MstStype",
  mst_stypes: "MstStype",
  mst_use_item: "MstUseItem",
  mst_use_items: "MstUseItem",
  night_support_airattack: "NightSupportAirattack",
  opening_airattack: "OpeningAirAttack",
  opening_airattack_list: "OpeningAirAttackList",
  opening_raigeki: "OpeningRaigeki",
  opening_taisen: "OpeningTaisen",
  opening_taisen_list: "OpeningTaisenList",
  own_deck: "OwnDeck",
  own_ship: "OwnShip",
  own_slotitem: "OwnSlotItem",
  plane_info: "PlaneInfo",
  support_airattack: "SupportAirattack",
  support_deck: "SupportDeck",
  support_hourai: "SupportHourai",
};

export function expectedSchemaNameForTable(table: string): string | null {
  if (!PUBLIC_RECORD_TABLES.has(table) && !MASTER_DATA_TABLES.has(table)) {
    return null;
  }
  return SCHEMA_NAMES[table] ?? null;
}