@startuml tables
entity mst_ship {
  + ship_id [PK]
  + lv [PK]
  --
  sortno [ソート番号]
  name [艦名]
  yomi [艦名よみ]
  stype [艦種]
  ctype [艦型]
  taik [耐久]
  souk [装甲]
  houg [砲撃]
  raig [雷撃]
  tyku [対空]
  tais [対潜]
  luck [運]
  soku [速力]
  leng [射程]
  slot_num [スロット数]
  maxeq [艦載機搭載機数]
  fuel_max [最大搭載燃料]
  bull_max [最大搭載弾薬]
}

entity mst_slot_item {
  + id [PK]
  --
  sortno [ソート番号]
  name [装備名]
  _type [種別]
  taik [耐久]
  souk [装甲]
  houg [砲撃]
  raig [雷撃]
  soku [速力]
  baku [爆装]
  tyku [対空]
  tais [対潜]
  houm [命中]
  houk [回避]
  saku [索敵]
  leng [射程]
  taibaku [対爆]
  geigeki [迎撃]
  distance [飛行距離]
}

entity mst_stype {
  + id [PK]
  --
  sortno [ソート番号]
  name [艦種名]
  equip_type [装備可能装備型]
}

entity mst_slot_item_equip_type {
  + id [PK]
  --
  name [装備種別名]
}

entity mst_equip_ship {
  + id [PK]
  --
  ship_id [艦船ID]
  equip_type [装備種別]
}

entity mst_equip_exslot {
  + id [PK]
  --
  ship_ids []
  stypes []
  ctypes []
  req_level [要求改修レベル]
}

entity ship {
  +id [PK]
  --
  ship_id [艦船ID]
  lv [レベル]
  cond [コンディション]
  nowhp [現在HP]
  maxhp [最大HP]
  soku [速力]
  leng [射程]
  slot [装備]
  onsolot [艦載機搭載数]
  slot_ex [補強増設]
  fuel [燃料]
  bull [弾薬]
  slotnum [装備スロット数]
  karyoku [火力]
  raisou [雷装]
  taiku [対空]
  soukou [装甲]
  kaihi [回避]
  taisen [対潜]
  sakuteki [索敵]
  lucky [運]
  sp_effect_items [海色リボン, 白たすき]
}

entity friend_ship {
  +id [PK]
  --
  ship_id [艦船ID]
  nowhp [現在HP]
  slot [装備]
  fuel [燃料]
  slotnum [装備スロット数]
  karyoku [火力]
  raisou [雷装]
  taiku [対空]
  soukou [装甲]
}

entity slot_item {
  +id [PK]
  --
  slotitem_id [装備ID]
  level [改修レベル]
  alv [熟練度]
}

entity decks {
  +id [PK]
  --
  ships [ 艦船ID ]
}

entity friend_decks {
  +id [PK]
  --
  ships [ 艦船ID ]
}

entity air_base {
  +id [PK]
  --
  action_kind [行動種別]
  plane_info [機体情報]
}

entity plane_info {
  +id [PK]
  --
  plane_id [機体ID]
  count [機数]
  max_count [最大機数]
}

' -----------------

entity enemy_decks {
  +id [PK]
  --
  ships [ 敵艦船ID ]
}

entity enemy_ship {
  +id [PK]
  --
  maxhp [最大HP]
  slot [装備]
  slotnum [装備スロット数]
  karyoku [火力]
  raisou [雷装]
  taiku [対空]
  soukou [装甲]
}

entity enemy_slot_item {
  +id [PK]
  --
  name [装備名]
}

'-----------------

entity map {
  +id [PK]
  --
  maparea_name [マップエリア名]
  maparea_id [マップエリアID]
  mapinfo_name [マップ情報名]
  mapinfo_no [マップ情報番号]
  bosscell_no [ボスセル番号]
  cell_data [セルデータ]
}

entity cell_data {
  +id [PK]
  --
  id [セルID]
  cell_no [セル番号]
  color_no [色]
  passed []
  distance [距離]
}

entity sortie {
  +id [PK]
  --
  map [マップId]
  battle [戦闘Id]
  destruction_battle [航空基地破壊Id]
  happenings [ハプニング]
  route [ルート]
}

entity battle {
  +id [PK]
  --
  enemy_deck [敵艦隊Id]
  friend_deck [味方艦隊Id]
  air_base [基地Id]
  result [戦闘結果]
  reliable [信頼性]
  
  timestamp [タイムスタンプ]
  midnight_timestamp [夜戦タイムスタンプ]
  cell_id [セルId]
  formation [陣形]
  total_damages_friends [味方艦ダメージ]
  total_damages_enemies [敵艦ダメージ]
  escape_idx [離脱艦]
  smoke_type [煙幕]
  air_base_assault: Option<AirBaseAssult>,
  carrier_base_assault: Option<CarrierBaseAssault>,
  air_base_air_attacks: Option<AirBaseAirAttacks>,
  friendly_task_force_attack: Option<FriendlyTaskForceAttack>,
  opening_air_attack: Option<OpeningAirAttack>,
  support_attack: Option<SupportAttack>,
  opening_taisen: Option<OpeningTaisen>,
  opening_raigeki: Option<OpeningRaigeki>,
  hougeki: Option<Vec<Option<Hougeki>>>,
  closing_raigeki: Option<ClosingRaigeki>,
  friendly_fleet_attack: Option<FriendlyFleetAttack>,
  midnight_flare_pos: Option<Vec<i64>>,
  midngiht_touchplane: Option<Vec<i64>>,
  midnight_hougeki: Option<MidnightHougeki>,
  f_nowhps [味方艦現在HP]
  e_nowhps [敵艦現在HP]
}

entity air_base_assault {
  +id [PK]
  --
  air_base_id [基地Id]
  air_base_attack [基地攻撃]
}

entity happening {
  +id [PK]
  --
  count [アイテム数]
  mst_id [アイテムID]
  dentan [電探有無]
}

entity destruction_battle {
  +id [PK]
  --
  timestamp [タイムスタンプ]
  formation [陣形]
  enemy_deck [敵艦隊Id]
  f_nowhps [味方艦現在HP]
  air_base_attack: AirBaseAttack
  lost_kind: [状態]
}

@enduml
